# app/routers/admin_product.py
"""
╔══════════════════════════════════════════════════════════════════╗
║         SkinSense — Admin Product Management                    ║
║                                                                  ║
║  Endpoints:                                                      ║
║   POST   /admin/product             Upload a new product        ║
║   GET    /admin/product             List all products           ║
║   GET    /admin/product/{id}        Get product by ID           ║
║   PUT    /admin/product/{id}        Update product              ║
║   DELETE /admin/product/{id}        Delete product              ║
║                                                                  ║
║  Schema (minimal, admin-friendly):                               ║
║   - image      → uploaded to AWS S3, URL stored                 ║
║   - name       → product display name                           ║
║   - categories → list of product categories (CSV string)        ║
║   - detected_conditions → skin/scalp conditions this product    ║
║                           targets (CSV string)                  ║
║   - id         → auto-generated MongoDB ObjectId (string)       ║
║                                                                  ║
║  Routine recommendation:                                         ║
║   Products are matched to detected conditions from scan results  ║
║   and surfaced by the AI routine generator via the              ║
║   find_products_for_conditions() helper.                        ║
╚══════════════════════════════════════════════════════════════════╝
"""

from __future__ import annotations

import io
import uuid
from datetime import datetime, timezone
from typing import Annotated, List, Optional

from bson import ObjectId
from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, UploadFile
from PIL import Image

from app.core.mongo_client import products_collection
from app.core.s3_client import delete_file_from_s3, upload_file_to_s3
from app.routers.admin_auth import _get_current_admin

router = APIRouter(
    prefix="/admin",
    tags=["Admin Products"],
    dependencies=[Depends(_get_current_admin)],
)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _csv_to_list(data: str) -> list[str]:
    """Convert a comma-separated string to a cleaned list of lowercase slugs."""
    return [x.strip().lower().replace(" ", "_") for x in data.split(",") if x.strip()]


def _doc_to_response(doc: dict) -> dict:
    """Serialize a MongoDB document for API response."""
    doc["id"] = str(doc.pop("_id"))
    return doc


async def _process_and_upload_image(file: UploadFile, product_id: str) -> tuple[str, str]:
    """
    Validates, resizes (to 480px wide), converts to JPEG, and uploads to S3.
    Returns (public_url, s3_key).
    """
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Only image files are accepted.")

    contents = await file.read()
    try:
        image = Image.open(io.BytesIO(contents))
        if image.mode not in ("RGB", "RGBA"):
            image = image.convert("RGB")
        elif image.mode == "RGBA":
            background = Image.new("RGB", image.size, (255, 255, 255))
            background.paste(image, mask=image.split()[3])
            image = background

        base_width = 480
        w_percent = base_width / float(image.size[0])
        h_size = int(float(image.size[1]) * float(w_percent))
        image = image.resize((base_width, h_size), Image.LANCZOS)

        buffer = io.BytesIO()
        image.save(buffer, format="JPEG", quality=85)
        buffer.seek(0)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Image processing failed: {exc}")

    s3_key = f"products/{product_id}.jpg"
    public_url = await upload_file_to_s3(buffer.read(), s3_key, "image/jpeg")
    return public_url, s3_key


# ── Routes ────────────────────────────────────────────────────────────────────

@router.post("/product", status_code=201, summary="Upload Product")
async def upload_product(
    file: UploadFile = File(..., description="Product image (JPEG/PNG/WebP)"),
    name: str = Form(..., description="Product display name"),
    categories: str = Form(..., description="Comma-separated categories, e.g. 'Cleanser, Serum'"),
    detected_conditions: str = Form(
        ...,
        description=(
            "Comma-separated skin/scalp conditions this product targets, "
            "e.g. 'acne, oiliness, dandruff'"
        ),
    ),
    price: Optional[float] = Form(None, description="Product price"),
):
    """
    Upload a new product. The ID is auto-generated by the backend.
    Image is resized to 480px wide and stored in AWS S3.
    """
    # Generate ID up-front so we can use it as the S3 key
    product_id = str(ObjectId())

    image_url, s3_key = await _process_and_upload_image(file, product_id)

    categories_list = _csv_to_list(categories)
    conditions_list = _csv_to_list(detected_conditions)

    doc = {
        "_id": ObjectId(product_id),
        "name": name.strip(),
        "image_url": image_url,
        "s3_key": s3_key,
        "categories": categories_list,
        "detected_conditions": conditions_list,
        "price": price,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    }
    products_collection.insert_one(doc)

    return {
        "success": True,
        "message": "Product uploaded successfully.",
        "id": product_id,
        "image_url": image_url,
        "name": name.strip(),
        "categories": categories_list,
        "detected_conditions": conditions_list,
        "price": price,
    }


@router.get("/product", summary="List Products")
async def list_products(
    search: Optional[str] = Query(None, description="Search by name"),
    condition: Optional[str] = Query(None, description="Filter by detected_condition slug"),
    category: Optional[str] = Query(None, description="Filter by category slug"),
    limit: int = Query(50, ge=1, le=200, description="Max results"),
    offset: int = Query(0, ge=0, description="Pagination offset"),
):
    """
    Return a paginated list of products with optional search/filter.
    """
    query: dict = {}
    if search:
        query["name"] = {"$regex": search, "$options": "i"}
    if condition:
        query["detected_conditions"] = condition.lower().replace(" ", "_")
    if category:
        query["categories"] = category.lower().replace(" ", "_")

    total = products_collection.count_documents(query)
    cursor = (
        products_collection.find(query)
        .sort("created_at", -1)
        .skip(offset)
        .limit(limit)
    )

    items = [_doc_to_response(doc) for doc in cursor]
    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "items": items,
    }


@router.get("/product/{product_id}", summary="Get Product")
async def get_product(product_id: str):
    """
    Fetch a single product by its auto-generated ID.
    """
    try:
        oid = ObjectId(product_id)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid product ID format.")

    doc = products_collection.find_one({"_id": oid})
    if not doc:
        raise HTTPException(status_code=404, detail="Product not found.")
    return _doc_to_response(doc)


@router.put("/product/{product_id}", summary="Update Product")
async def update_product(
    product_id: str,
    file: Optional[UploadFile] = File(None, description="New product image (optional)"),
    name: Optional[str] = Form(None, description="Updated product name"),
    categories: Optional[str] = Form(None, description="Updated categories (CSV)"),
    detected_conditions: Optional[str] = Form(None, description="Updated target conditions (CSV)"),
    price: Optional[float] = Form(None, description="Updated product price"),
):
    """
    Partially update a product. Only provided fields are changed.
    If a new image is supplied the old S3 object is replaced.
    """
    try:
        oid = ObjectId(product_id)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid product ID format.")

    existing = products_collection.find_one({"_id": oid})
    if not existing:
        raise HTTPException(status_code=404, detail="Product not found.")

    updates: dict = {"updated_at": datetime.now(timezone.utc)}

    if name is not None:
        updates["name"] = name.strip()
    if categories is not None:
        updates["categories"] = _csv_to_list(categories)
    if detected_conditions is not None:
        updates["detected_conditions"] = _csv_to_list(detected_conditions)
    if price is not None:
        updates["price"] = price

    if file and file.filename:
        image_url, s3_key = await _process_and_upload_image(file, product_id)
        updates["image_url"] = image_url
        updates["s3_key"] = s3_key

    products_collection.update_one({"_id": oid}, {"$set": updates})

    doc = products_collection.find_one({"_id": oid})
    return {
        "success": True,
        "message": "Product updated successfully.",
        "data": _doc_to_response(doc),
    }


@router.delete("/product/{product_id}", summary="Delete Product")
async def delete_product(product_id: str):
    """
    Delete a product and remove its image from S3.
    """
    try:
        oid = ObjectId(product_id)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid product ID format.")

    doc = products_collection.find_one({"_id": oid})
    if not doc:
        raise HTTPException(status_code=404, detail="Product not found.")

    # Remove image from S3
    s3_key = doc.get("s3_key") or f"products/{product_id}.jpg"
    try:
        await delete_file_from_s3(s3_key)
    except Exception as exc:
        print(f"[WARN] S3 delete failed for {s3_key}: {exc}")

    products_collection.delete_one({"_id": oid})
    return {"success": True, "message": "Product deleted successfully."}


# ── Public helper for the routine generator ───────────────────────────────────

def find_products_for_conditions(
    conditions: list[str],
    limit: int = 5,
) -> list[dict]:
    """
    Return up to `limit` products whose detected_conditions overlap
    with the given list of condition slugs. Used by the AI routine generator
    to surface real product recommendations.

    Returns lightweight dicts with: id, name, image_url, categories,
    detected_conditions.
    """
    if not conditions:
        return []

    normalised = [c.strip().lower().replace(" ", "_") for c in conditions if c]
    cursor = products_collection.find(
        {"detected_conditions": {"$in": normalised}},
        {"name": 1, "image_url": 1, "categories": 1, "detected_conditions": 1},
    ).limit(limit)

    results = []
    for doc in cursor:
        results.append({
            "id": str(doc["_id"]),
            "name": doc.get("name", ""),
            "image_url": doc.get("image_url", ""),
            "categories": doc.get("categories", []),
            "detected_conditions": doc.get("detected_conditions", []),
        })
    return results